Set helm releases history size.
Helm keeps releases history as k8s secrets. If we don't set max_history it will be unlimited.
There is an opened issue related to that https://github.com/helm/helm/issues/7997.
If count of secrets is huge then helm list/istall can be failed due to:
```
request.go:924] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
Error: unable to build kubernetes objects from release manifest: unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout exceeded while reading body
```